// SPDX-License-Identifier: Apache-2.0

import Foundation

enum PromptBuilder {
    /// Shared product contract — prepended to every mode.
    static let core = """
    You are Peeknook, a local-first practice copilot on macOS. The user explicitly captured \
    what is on their screen; you receive a screenshot of what they captured — a specific window or \
    their whole screen — and sometimes extracted text. \
    Answer from what is actually visible — do not invent UI, text, or questions that are not there. \
    If the screen is ambiguous, state your best inference in one short line, then answer. \
    Keep responses readable in a small notch HUD unless the screen clearly requires numbered steps.
    """

    static func systemPrompt(for mode: PracticeMode) -> String {
        switch mode {
        case .general, .korean:
            """
            \(core)
            Behave like a capable screen-aware assistant (not a generic chatbot). \
            FIRST read the actual visible text — titles, headings, labels, prices, buttons, code, errors, subtitles — and identify specifically what app, site, or content this is. Name it concretely. \
            THEN give the single most useful, specific thing: answer the visible question, explain the concept, debug the error, gloss the non-English text, or summarize the key point. \
            Do NOT just describe the layout ("a form with two columns") — that is useless. And NEVER ask the user what they want or what they are trying to do; they captured this screen for help, so help with what is visible. \
            When non-English text is prominent (e.g. Korean subtitles or lesson UI), lead with a short English gloss or translation (≤3 lines). \
            Be direct and specific. Default length: 4–8 short lines. No filler ("Sure!", "Based on the image", "It looks like").
            """
        case .explain:
            """
            \(core)
            Explain what is on screen clearly in ≤5 short lines.
            """
        case .code:
            """
            \(core)
            Code practice: hint ladder — nudge first, not a full solution. ≤5 lines unless an error message needs unpacking.
            """
        case .chessCoach:
            """
            \(core)
            Chess coaching for solo/bot study: themes and plans only, not engine lines. ≤4 lines.
            """
        }
    }

    static func userMessage(
        capture: CaptureResult,
        mode: PracticeMode,
        quick: Bool = false,
        webLookup: WebLookupSnapshot? = nil
    ) -> String {
        var parts: [String] = [
            "The user pressed capture. Mode: \(mode.displayName).",
            "Source: \(capture.sourceLabel)."
        ]

        if capture.appName != nil || capture.windowTitle != nil {
            // Honest capture identity — helps grounding, but the screenshot is ground truth.
            parts.append("Captured: \(capture.targetLabel).")
        }

        if capture.hasVision {
            parts.append("A screenshot is attached to this message (vision).")
        }

        if let text = capture.text, !text.isEmpty {
            parts.append("""
            Supplementary extracted text (may be incomplete — prefer the screenshot when they disagree):
            ---
            \(text)
            ---
            """)
        } else {
            parts.append("No reliable extracted text — rely on the screenshot.")
        }

        if let webLookup, !webLookup.results.isEmpty {
            parts.append(WebSearchClient.promptContext(from: webLookup))
        }

        if quick {
            parts.append("Quick mode: answer in at most 2–3 short lines. Lead with the single most useful point; no preamble.")
        }

        parts.append("Answer from what is on screen.")
        return parts.joined(separator: "\n\n")
    }

    // MARK: - Follow-up suggestions (generated by a separate, schema-constrained call)

    /// System prompt for the dedicated suggestion pass. The model proposes the next questions
    /// the user is most likely to ask about *this* screen — grounded, never generic.
    static let followUpSystemPrompt = """
    You generate follow-up question suggestions for a screen-aware assistant. \
    Given the screenshot, the conversation, and the latest answer, propose the 2–3 questions the \
    user is most likely to ask NEXT about this specific screen. \
    Rules: phrase each as the user would type it (first person, e.g. "How do I fix this?"); \
    keep each under 8 words; make them specific to what is visible, not generic; \
    do not repeat questions already answered. Return only the requested JSON.
    """

    static let followUpUserPrompt =
        "Suggest the 2–3 best follow-up questions for this screen and answer."

    /// JSON schema handed to Ollama's `format` so generation is grammar-constrained to a clean
    /// array — no string-marker parsing, reliable across models.
    static var followUpSchema: [String: Any] {
        [
            "type": "object",
            "properties": [
                "suggestions": [
                    "type": "array",
                    "items": ["type": "string"],
                    "maxItems": 3
                ]
            ],
            "required": ["suggestions"]
        ]
    }
}
